theme: minima
title: Angie Hub 
author: Angie Singh
email: asingh3@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is an amazing webite! My first github website ever! 

# social links
instagram_username: angie.malleaa
github_username:  angie199876

show_excerpts: true # set to false to remove excerpts on the homepage
